language: node_js
node_js:
  - "node"

before_install:
  - npm install -g gulp
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - gulp dist
  - gulp dist -e production
